services:
  - type: web
    name: crm-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.16.0

  - type: static
    name: crm-frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishDir: ./dist
